# Site settings
title: jonathan leopard | Webdev & Devops
tag_text: Jonathan leopard
description: Simple landing page for jonathanleopard.com

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
